routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function(){

    Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['admin']], function(){
      Route::get('/', 'DashboardController@dashboard')->name('admin.index');
      Route::resource('/category', 'CategoryController', ['as'=>'admin']);
      Route::resource('/product', 'ProductController', ['as'=>'admin']);
      Route::resource('/attribute', 'AttributeController', ['as'=>'admin']);
      Route::resource('/tag', 'TagController', ['as'=>'admin']);
      Route::resource('/news', 'NewsController', ['as'=>'admin']);
      Route::resource('/newsimage', 'NewsimageController', ['as'=>'admin']);
      Route::resource('/orders', 'OrderController', ['as'=>'admin']);
      Route::resource('/manufacturers', 'ManufacturerController', ['as'=>'admin']);
      Route::resource('/info', 'InfoController', ['as'=>'admin']);
      Route::resource('/review', 'ReviewController', ['as'=>'admin']);
      Route::resource('/vendorreview', 'VendorReviewController', ['as'=>'admin']);
      Route::resource('/callback', 'CallbackController', ['as'=>'admin']);
      Route::post('/product/offer', 'ProductController@saveOffer')->name('admin.product.offer');
      Route::post('/product/deleteimage', 'ProductController@deleteImage')->name('admin.product.deleteimage');
      Route::post('/product/deletepicture', 'ProductController@deletePicture')->name('admin.product.deletepicture');
      Route::post('/product/autocomplete', 'ProductController@autocomplete')->name('admin.product.autocomplete');
      Route::post('/product/autocomplete2', 'ProductController@autocomplete2')->name('admin.product.autocomplete2');
      Route::put('/property/saveproperty', 'PropertyController@saveProperty')->name('admin.property.saveproperty'); 
      Route::post('/category/deleteicon', 'CategoryController@deleteIcon')->name('admin.category.deleteicon');
      Route::post('/category/deleteimage', 'CategoryController@deleteImage')->name('admin.category.deleteimage');
      Route::post('/news/deletepicture', 'NewsController@deletePicture')->name('admin.news.deletepicture');
      Route::post('/order/savepurchase', 'OrderController@savePurchase')->name('admin.order.savepurchase');
      Route::post('/order/autocomplete', 'OrderController@autocomplete')->name('admin.order.autocomplete');
      Route::post('/order/savepurchase', 'OrderController@savePurchase')->name('admin.order.savepurchase');
      Route::post('/order/setprice', 'OrderController@setPrice');

      Route::get('/import', 'ImportController@index')->name('import');
      Route::post('/upload', 'ImportController@upload')->name('admin.upload');

      Route::group(['prefix'=>'user_management', 'namespace'=>'UserManagement'], function(){
        Route::resource('/user', 'UserController', ['as'=>'admin.user_management']);
        Route::resource('/role', 'UserRoleController', ['as'=>'admin.user_management']);
        Route::resource('/orderplan', 'OrdersPlanController', ['as'=>'admin.user_management']);
        Route::resource('/adv', 'AdvController', ['as'=>'admin.user_management']);
      });
    });

    Route::get('/', 'WelcomeController@main')->name('main');
    Route::post('/uploadfile', 'ProductController@upload')->name('upload');
    Route::post('/addtowishlist', 'ProductController@add_wishlist');
    Route::post('/addcompare', 'ProductController@add_compare');
    Route::get('/compare', 'ProductController@compare')->name('compare');
    Route::get('/removecompare/{id}', 'ProductController@removeCompare');
    Route::get('/search/product', 'ProductController@search')->name('search.product');
    
    Route::get('/cart', 'CartController@index')->name('cart');
    Route::post('/add_to_cart', 'CartController@add')->name('add_to_cart');
    Route::post('/map', 'CartController@map');
    Route::delete('/remove_from_cart/{cart}', 'CartController@remove');
    Route::put('/update_cart/{cart}', 'CartController@update');
    Route::post('/setshipping/{vendor}', 'CartController@setShippingMethod');
    Route::get('/preorder', 'CartController@preorder')->name('preorder');
    Route::post('/setorder', 'OrderController@setOrder');
    Route::get('/success/{id}', 'OrderController@confirm');
    Route::get('/order_info/{id}', 'OrderController@info')->name('order_info');
    Route::post('/shopaddresses', 'OrderController@getDelivery');
    Route::post('/costdelivery', 'OrderController@costDelivery');
    Route::post('/sessioncost', 'OrderController@sessionCost');
    Route::post('/mincost', 'OrderController@mincost');

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/homeedit', 'HomeController@edit')->name('edithome');
    Route::put('/homeedit/{user}', 'HomeController@update')->name('updatehome');
    Route::post('/changepassword', 'HomeController@changePassword')->name('changepassword');
    Route::put('/homeeditvendor/{user}', 'HomeController@updatevendor')->name('updatehomevendor');
    Route::post('/orderplan', 'HomeController@orderPlan');
    Route::post('/orderadv', 'HomeController@orderAdv')->name('orderadv');
    Route::put('/selectstatus', 'HomeController@selectStatus')->name('selectstatus');
    Route::post('/deleteavatar', 'HomeController@deleteAvatar');
    Route::post('/addvendorreview', 'HomeController@addReview')->name('addvendorreview');
    Route::delete('/deletevendorreview', 'HomeController@deleteVendorReview');
    Route::delete('/deleteproductreview', 'HomeController@deleteProductReview');
    Route::get('/cron', 'HomeController@cron');
    Route::delete('/removeshop', 'HomeController@removeShop');
    Route::post('/addshop', 'HomeController@addShop');
    Route::post('/adddelivery', 'HomeController@addDelivery');
    Route::put('/activeshop', 'HomeController@setActiveShop');
    Route::delete('/removedelivery', 'HomeController@removeDelivery');
    Route::post('/sendactivate', 'HomeController@sendMessage')->name('sendactivate');
    Route::get('/categories', 'CategoryController@index')->name('categories');
    Route::get('/filters/{id}', 'CategoryController@filters')->name('filters');
    Route::get('/category/{id}', 'CategoryController@show')->name('category');
    Route::get('/product/{id}', 'ProductController@show')->name('product');
    Route::post('/addproduct', 'ProductController@toModeration')->name('addproduct');
    Route::get('/is_sale', 'ProductController@is_sale')->name('is_sale');
    Route::get('/by_vendor/{id}', 'ProductController@byVendor')->name('by_vendor');

    Route::post('/addreview', 'ReviewController@add')->name('addreview');
    Route::post('/vlike', 'ReviewController@v_like');
    Route::post('/vdislike', 'ReviewController@v_dislike');
    Route::post('/plike', 'ReviewController@p_like');
    Route::post('/pdislike', 'ReviewController@p_dislike');

    Route::get('/newslist', 'NewsController@index')->name('newslist');
    Route::get('/news/{id}', 'NewsController@show')->name('news');
    Route::get('/tag/{id}', 'NewsController@tag')->name('tag');
    Route::get('/search/news', 'NewsController@search')->name('searchnews');

    Route::get('/charity', 'CharityController@index')->name('charity');

    Route::get('/info/{id}', 'InfoController@index')->name('info');
    Route::get('/contact', 'InfoController@contact')->name('contact');
    Route::post('/callback', 'InfoController@callback')->name('callback');

    Route::get('/api_login', 'ApiController@login');
    Route::post('/api_register', 'ApiController@register');
    Route::get('/api_products/{id}', 'ApiController@getProducts');
    Route::post('/api_result', 'ApiController@result');
    Route::post('/api_reset_password', 'ApiController@resetPassword');
    Route::post('/api_update_password', 'ApiController@updatePassword');

    Route::resource('/photos', 'PhotostockController');
});


Route::get('setlocale/{lang}', function ($lang) {

    $referer = Redirect::back()->getTargetUrl();; //URL предыдущей страницы
    $parse_url = parse_url($referer, PHP_URL_PATH); //URI предыдущей страницы

    //разбиваем на массив по разделителю
    $segments = explode('/', $parse_url);

    //Если URL (где нажали на переключение языка) содержал корректную метку языка
    if (in_array($segments[1], App\Http\Middleware\LocaleMiddleware::$languages)) {

        unset($segments[1]); //удаляем метку
    } 
    
    //Добавляем метку языка в URL (если выбран не язык по-умолчанию)
    if($lang != 'uk'){
      array_splice($segments, 1, 0, $lang); 
    }
    

    //формируем полный URL
    $url = Request::root().implode("/", $segments);
    
    //если были еще GET-параметры - добавляем их
    if(parse_url($referer, PHP_URL_QUERY)){
        $url = $url.'?'. parse_url($referer, PHP_URL_QUERY);
    }
    return redirect($url); //Перенаправляем назад на ту же страницу                            

})->name('setlocale');

app/Models/Attribute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Attribute extends Model
{
    protected $guarded = [];

    public function prorerties()
    {
        return $this->hasMany(Property::class);
    }
}

app/Http/Controllers/Admin/AttributeController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Attribute;
use App;

class AttributeController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.attributes.index', [
            'attributes' => Attribute::orderBy('created_at', 'desc')->paginate(10),
            'local' => App::getLocale()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.attributes.create', [
            'attribute' => [],
            'local' => App::getLocale()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $attribute = Attribute::create($request->all());
        request()->session()->flash('success', 'Характеристика успешно создана');
        return redirect()->route('admin.attribute.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Attribute $attribute)
    {
        return view('admin.attributes.edit', [
            'attribute' => $attribute,
            'local' => App::getLocale()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Attribute $attribute)
    {
        $attribute->name_ru = $request['name_ru'];
        $attribute->name_uk = $request['name_uk'];
        $attribute->save();
        request()->session()->flash('success', 'Данные обновлены');
        return redirect()->route('admin.attribute.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Attribute $attribute)
    {
        $attribute->delete();
        request()->session()->flash('success', 'Заявка удалена');
        return redirect()->route('admin.attribute.index');
    }
}

resources/views/admin/attributes/create.blade.php
@extends('admin.layouts.app')

@section('content')

<div class="container">
	@component('admin.components.breadcrumb')
	@slot('title') Создать характеристику @endslot
	@slot('parent') Главная страница @endslot
	@slot('active') Характеристики @endslot
	@endcomponent
	<hr/>
	<form action="{{ route('admin.attribute.store') }}" method="post" class="form-horizontal">
		{{ csrf_field() }}
		@include('admin.attributes.partials.form')
	</form>
</div>

@endsection

resources/views/admin/attributes/edit.blade.php
@extends('admin.layouts.app')

@section('content')

<div class="container">
	@component('admin.components.breadcrumb')
	@slot('title') Редактировать характеристику @endslot
	@slot('parent') Главная страница @endslot
	@slot('active') Характеристики @endslot
	@endcomponent
	<hr/>
	<form action="{{ route('admin.attribute.update', $attribute) }}" method="post" class="form-horizontal">
		{{ csrf_field() }}
		<input type="hidden" name="_method" value="put">
		@include('admin.attributes.partials.form')
	</form>
</div>

@endsection

resources/views/admin/attributes/index.blade.php
@php
$attr_title = 'name_' . $local;
@endphp

@extends('admin.layouts.app')

@section('content')

<div class="container">
	@component('admin.components.breadcrumb')
	@slot('title') Список Характеристик @endslot
	@slot('parent') Главная страница @endslot
	@slot('active') Характеристики @endslot
	@endcomponent
	<hr/>
	@if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if (Session::has('success'))
        <div class="alert alert-success">{{ Session::get('success') }}</div>
    @endif
	<a href="{{ route('admin.attribute.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus-square-o"> Создать характеристику</i></a>
	<table class="table table-striped">
		<thead>
			<th>Название</th>
			<th>Статус</th>
			<th class="text-right">Действия</th>
		</thead>
		<tbody>
			@forelse($attributes as $attribute)
			<tr>
				<td>{{ $attribute->$attr_title }}</td>
				<td>{{ $attribute->published }}</td>
				<td class="text-right">
				    <form action="{{ route('admin.attribute.destroy', $attribute) }}" onsubmit="if(confirm('Delete?')){return true}else{return false}" method="post">
            			<input type="hidden" name="_method" value="DELETE"> 
            			{{ csrf_field() }}
            			<a href="@if(in_array($attribute->id, [10])) # @else {{ route('admin.attribute.edit', $attribute) }} @endif" class="btn btn-default" @if(in_array($attribute->id, [6, 7, 8, 9, 10])) disabled @endif><i class="fa fa-edit"></i></a>
            			<button type="submit" class="btn" @if(in_array($attribute->id, [6, 7, 8, 9, 10]))) disabled @endif><i class="fa fa-trash"></i></button>
            		</form></td> 
			</tr>
			@empty
			<tr>
				<td colspan="3" class="text-center">Нет характеристик</td>
			</tr>
			@endforelse
		</tbody>
		<tfoot>
			<tr>
				<td colspan="3">
					<ul class="pagination full-right">
						{{ $attributes->links() }}
					</ul>
				</td>
			</tr>
		</tfoot>
	</table>
</div>

@endsection